name: build

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - v*

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [all, no_gui]
        compiler: [g++, clang++]

    name: linux-${{ matrix.target }}-${{ matrix.compiler }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Prepare system
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update

      - name: Install base dependencies
        run: |
          sudo apt-get install -y libasound2-dev

      - name: Install ui dependencies
        if: ${{ matrix.target == 'all' }}
        run: |
          sudo apt-get install -y qtbase5-dev libqwt-qt5-dev

      - name: Build
        env:
          CXX: ${{ matrix.compiler }}
          LD: ${{ matrix.compiler }}
          CXXFLAGS: -Werror
        run: make ${{ matrix.target }}

      - name: Check cli
        run: ./bin/signal-estimator -h

      - name: Check ui
        if: ${{ matrix.target == 'all' }}
        run: test -e ./bin/signal-estimator-gui
