name: build

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:

  linux-x86_64:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [all, no_gui]
        compiler: [g++, clang++]

    name: linux-x86_64-${{ matrix.target }}-${{ matrix.compiler }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install base dependencies
        run: |
          sudo apt-get install -y libasound2-dev

      - name: Install ui dependencies
        if: ${{ matrix.target == 'all' }}
        run: |
          sudo apt-get install -y qtbase5-dev libqwt-qt5-dev

      - name: Build
        env:
          CXX: ${{ matrix.compiler }}
          LD: ${{ matrix.compiler }}
          CXXFLAGS: -Werror
        run: make ${{ matrix.target }}

      - name: Check cli
        run: ./bin/x86_64-linux-gnu/signal-estimator -h

      - name: Check ui
        if: ${{ matrix.target == 'all' }}
        run: test -e ./bin/x86_64-linux-gnu/signal-estimator-gui

  linux-arm32:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: make arm32

      - name: Check
        run: test -e ./bin/arm-linux-gnueabihf/signal-estimator

  linux-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: make arm64

      - name: Check
        run: test -e ./bin/aarch64-linux-gnu/signal-estimator
